{"timestamp": "2024-03-03 14:00:59.680243", "exception": "user forced crash", "traceback": "Traceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 468, in main\n    raise Exception(\"user forced crash\")\nException: user forced crash\n", "variables": "[array([231. ,   0.8, 450. ]), array([270.,   0.,   0.]), 0, 2050, [], []]", "usertext": "c", "checksum": "7bcf996cb872ac03e5bcc097a236b98c", "systemDetails": ["Linux", "adrian", "6.5.0-21-generic", "#21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2", "x86_64"], "logchecksum": "0cf6669bdce1b666e0699b029613dcfb", "sent": 1}