{"timestamp": "2024-03-03 14:12:01.230251", "exception": "user forced crash", "traceback": "Traceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 468, in main\n    raise Exception(\"user forced crash\")\nException: user forced crash\n", "variables": "[array([231. ,   0.8, 450. ]), array([270.,   0.,   0.]), 1000.0, 1965, [], []]", "usertext": "", "checksum": "818c68e015af2813782d2a3aea6f1838", "systemDetails": ["Linux", "adrian", "6.5.0-21-generic", "#21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2", "x86_64"], "logchecksum": "15365b37113a204cab69f6a3d23ca55b", "sent": 1}