{
    "timestamp": "2024-03-03 14:13:50.231984",
    "exception": "user forced crash",
    "traceback": "Traceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 468, in main\n    raise Exception(\"user forced crash\")\nException: user forced crash\n",
    "variables": "[array([231. ,   0.8, 450. ]), array([270.,   0.,   0.]), 1000, 1992, [], []]",
    "usertext": "",
    "checksum": "76b95d255c62606bc673478e3eb54855",
    "systemDetails": [
        "Linux",
        "adrian",
        "6.5.0-21-generic",
        "#21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2",
        "x86_64"
    ],
    "logchecksum": "452d5fd79cce566539625c6314b6479f",
    "sent": 1
}