{"timestamp": "2024-03-03 14:55:31.301902", "exception": "user forced crash", "traceback": "Traceback (most recent call last):\n  File \"/home/adrian/Documents/GitHub/wdhs-alevel-flight-sim/OpenPyFlySim/flight_sim.py\", line 468, in main\n    raise Exception(\"user forced crash\")\nException: user forced crash\n", "variables": "[array([231. ,   0.8, 450. ]), array([270.,   0.,   0.]), 0, 2020, [], []]", "usertext": "", "checksum": "39ed8aaa4c4d066818e4d7c78f5625d4", "systemDetails": ["Linux", "adrian", "6.5.0-21-generic", "#21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2", "x86_64"], "logchecksum": "b575a41d648a68306f24e12c539a9d40", "sent": 1}